/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/0 — generated by GEMINI.
 * Task: HE-000_hasCloseElements
 */
public class HE000_hasCloseElements {
    /**
     * Check if in given list of numbers, are any two numbers closer to each other than given threshold.
     *     >>> hasCloseElements(Arrays.asList(1.0, 2.0, 3.0), 0.5)
     *     false
     *     >>> hasCloseElements(Arrays.asList(1.0, 2.8, 3.0, 4.0, 5.0, 2.0), 0.3)
     *     true
     */
    public boolean hasCloseElements(List<Double> numbers, double threshold) {
        return numbers.stream()
                .flatMap(a -> numbers.stream().map(b -> Math.abs(a - b)))
                .filter(d -> d > 0)
                .anyMatch(d -> d < threshold);
    }
}
