/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/3 — generated by GEMINI.
 * Task: HE-003_belowZero
 */
public class HE003_belowZero {
    /**
     * You're given a list of deposit and withdrawal operations on a bank account that starts with
     *     zero balance. Your task is to detect if at any point the balance of account fallls below zero, and
     *     at that point function should return True. Otherwise it should return False.
     *     >>> belowZero(Arrays.asList(1, 2, 3))
     *     false
     *     >>> belowZero(Arrays.asList(1, 2, -4, 5))
     *     true
     */
    public boolean belowZero(List<Integer> operations) {
        int balance = 0;
        for (Integer op : operations) {
            balance += op;
            if (balance < 0) {
                return true;
            }
        }
        return false;
    }
}
