/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/9 — generated by GEMINI.
 * Task: HE-009_rollingMax
 */
public class HE009_rollingMax {
    /**
     * From a given list of integers, generate a list of rolling maximum element found until given moment
     *     in the sequence.
     *     >>> rollingMax(Arrays.asList(1, 2, 3, 2, 3, 4, 2))
     *     [1, 2, 3, 3, 3, 4, 4]
     */
    public List<Integer> rollingMax(List<Integer> numbers) {
        List<Integer> result = new ArrayList<>();
        int currentMax = Integer.MIN_VALUE;
        for (int n : numbers) {
            if (n > currentMax) currentMax = n;
            result.add(currentMax);
        }
        return result;
    }
}
