/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/9 — generated by GEMINI.
 * Task: HE-009_rollingMax
 */
public class HE009_rollingMax {
    /**
     * From a given list of integers, generate a list of rolling maximum element found until given moment
     *     in the sequence.
     *     >>> rollingMax(Arrays.asList(1, 2, 3, 2, 3, 4, 2))
     *     [1, 2, 3, 3, 3, 4, 4]
     */
    public List<Integer> rollingMax(List<Integer> numbers) {
        List<Integer> result = new ArrayList<>();
        int currentMax = Integer.MIN_VALUE;
        for (int n : numbers) {
            if (n > currentMax) currentMax = n;
            result.add(currentMax);
        }
        return result;
    }
}
