/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/0 — generated by GEMINI.
 * Task: HE-000_hasCloseElements
 */
public class HE000_hasCloseElements {
    /**
     * Check if in given list of numbers, are any two numbers closer to each other than given threshold.
     *     >>> hasCloseElements(Arrays.asList(1.0, 2.0, 3.0), 0.5)
     *     false
     *     >>> hasCloseElements(Arrays.asList(1.0, 2.8, 3.0, 4.0, 5.0, 2.0), 0.3)
     *     true
     */
    public boolean hasCloseElements(List<Double> numbers, double threshold) {
        for (int i = 0; i < numbers.size(); i++) {
            for (int j = i + 1; j < numbers.size(); j++) {
                if (Math.abs(numbers.get(i) - numbers.get(j)) < threshold) {
                    return true;
                }
            }
        }
        return false;
    }
}
