/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/7 — generated by GEMINI.
 * Task: HE-007_filterBySubstring
 */
public class HE007_filterBySubstring {
    /**
     * Filter an input list of strings only for ones that contain given substring
     *     >>> filterBySubstring(List.of(), "a")
     *     []
     *     >>> filterBySubstring(Arrays.asList("abc", "bacd", "cde", "array"), "a")
     *     ["abc", "bacd", "array"]
     */
    public List<String> filterBySubstring(List<String> strings, String substring) {
        List<String> result = new ArrayList<>();
        for (String s : strings) {
            if (s.contains(substring)) result.add(s);
        }
        return result;
    }
}
