/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/7 — generated by GEMINI.
 * Task: HE-007_filterBySubstring
 */
public class HE007_filterBySubstring {
    /**
     * Filter an input list of strings only for ones that contain given substring
     *     >>> filterBySubstring(List.of(), "a")
     *     []
     *     >>> filterBySubstring(Arrays.asList("abc", "bacd", "cde", "array"), "a")
     *     ["abc", "bacd", "array"]
     */
    public List<String> filterBySubstring(List<String> strings, String substring) {
        List<String> result = new ArrayList<>();
        for (String s : strings) {
            if (s.contains(substring)) result.add(s);
        }
        return result;
    }
}
