/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/11 — generated by GEMINI.
 * Task: HE-011_stringXor
 */
public class HE011_stringXor {
    /**
     * Input are two strings a and b consisting only of 1s and 0s.
     *     Perform binary XOR on these inputs and return result also as a string.
     *     >>> stringXor("010", "110")
     *     "100"
     */
    public String stringXor(String a, String b) {
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < a.length(); i++) {
            result.append(a.charAt(i) == b.charAt(i) ? '0' : '1');
        }
        return result.toString();
    }
}
