/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/11 — generated by GEMINI.
 * Task: HE-011_stringXor
 */
public class HE011_stringXor {
    /**
     * Input are two strings a and b consisting only of 1s and 0s.
     *     Perform binary XOR on these inputs and return result also as a string.
     *     >>> stringXor("010", "110")
     *     "100"
     */
    public String stringXor(String a, String b) {
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < a.length(); i++) {
            result.append(a.charAt(i) == b.charAt(i) ? '0' : '1');
        }
        return result.toString();
    }
}
