/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/15 — generated by GEMINI.
 * Task: HE-015_stringSequence
 */
public class HE015_stringSequence {
    /**
     * Return a string containing space-delimited numbers starting from 0 upto n inclusive.
     *     >>> stringSequence(0)
     *     "0"
     *     >>> stringSequence(5)
     *     "0 1 2 3 4 5"
     */
    public String stringSequence(int n) {
        return java.util.stream.IntStream.rangeClosed(0, n)
                .mapToObj(Integer::toString)
                .collect(java.util.stream.Collectors.joining(" "));
    }
}
