/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/10 — generated by GEMINI.
 * Task: HE-010_isPalindrome
 */
public class HE010_isPalindrome {
    public boolean isPalindrome(String string) {
        int i = 0;
        int j = string.length() - 1;
        while (i < j) {
            if (string.charAt(i) != string.charAt(j)) {
                return false;
            }
            i++;
            j--;
        }
        return true;
    }
    /**
     * Test if given string is a palindrome
     */
    public String makePalindrome(String string) {
        if (string == null || string.isEmpty()) return string;
        int i;
        for (i = 0; i < string.length(); i++) {
            if (isPalindrome(string.substring(i))) break;
        }
        return string + new StringBuilder(string.substring(0, i)).reverse().toString();
    }
}
