/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/10 — generated by GEMINI.
 * Task: HE-010_isPalindrome
 */
public class HE010_isPalindrome {
    public boolean isPalindrome(String string) {
        int i = 0;
        int j = string.length() - 1;
        while (i < j) {
            if (string.charAt(i) != string.charAt(j)) {
                return false;
            }
            i++;
            j--;
        }
        return true;
    }
    /**
     * Test if given string is a palindrome
     */
    public String makePalindrome(String string) {
        if (string == null || string.isEmpty()) return string;
        int i;
        for (i = 0; i < string.length(); i++) {
            if (isPalindrome(string.substring(i))) break;
        }
        return string + new StringBuilder(string.substring(0, i)).reverse().toString();
    }
}
