/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/15 — generated by GEMINI.
 * Task: HE-015_stringSequence
 */
public class HE015_stringSequence {
    /**
     * Return a string containing space-delimited numbers starting from 0 upto n inclusive.
     *     >>> stringSequence(0)
     *     "0"
     *     >>> stringSequence(5)
     *     "0 1 2 3 4 5"
     */
    public String stringSequence(int n) {
        return java.util.stream.IntStream.rangeClosed(0, n)
                .mapToObj(Integer::toString)
                .collect(java.util.stream.Collectors.joining(" "));
    }
}
