/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/25 — generated by GEMINI.
 * Task: HE-025_factorize
 */
public class HE025_factorize {
    /**
     * Return list of prime factors of given integer in the order from smallest to largest.
     *     Each of the factors should be listed number of times corresponding to how many times it appeares in factorization.
     *     Input number should be equal to the product of all factors
     *     >>> factorize(8)
     *     [2, 2, 2]
     *     >>> factorize(25)
     *     [5, 5]
     *     >>> factorize(70)
     *     [2, 5, 7]
     */
    public List<Integer> factorize(int n) {
        List<Integer> factors = new ArrayList<>();
        int x = n;
        int d = 2;
        while (x > 1) {
            while (x % d == 0) {
                factors.add(d);
                x /= d;
            }
            d++;
        }
        return factors;
    }
}
