/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/28 — generated by GEMINI.
 * Task: HE-028_concatenate
 */
public class HE028_concatenate {
    /**
     * Concatenate list of strings into a single string
     *     >>> concatenate(List.of())
     *     ""
     *     >>> concatenate(Arrays.asList("a", "b", "c"))
     *     "abc"
     */
    public String concatenate(List<String> strings) {
        return String.join("", strings);
    }
}
