/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/21 — generated by GEMINI.
 * Task: HE-021_rescaleToUnit
 */
public class HE021_rescaleToUnit {
    /**
     * Given list of numbers (of at least two elements), apply a linear transform to that list,
     *     such that the smallest number will become 0 and the largest will become 1
     *     >>> rescaleToUnit(Arrays.asList(1.0, 2.0, 3.0, 4.0, 5.0))
     *     [0.0, 0.25, 0.5, 0.75, 1.0]
     */
    public List<Double> rescaleToUnit(List<Double> numbers) {
        double min = Collections.min(numbers);
        double max = Collections.max(numbers);
        double range = max - min;
        return numbers.stream().map(n -> (n - min) / range).collect(java.util.stream.Collectors.toList());
    }
}
