/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/23 — generated by GEMINI.
 * Task: HE-023_strlen
 */
public class HE023_strlen {
    /**
     * Return length of given string
     *     >>> strlen("")
     *     0
     *     >>> strlen("abc")
     *     3
     */
    public int strlen(String string) {
        return string.length();
    }
}
