/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/23 — generated by GEMINI.
 * Task: HE-023_strlen
 */
public class HE023_strlen {
    /**
     * Return length of given string
     *     >>> strlen("")
     *     0
     *     >>> strlen("abc")
     *     3
     */
    public int strlen(String string) {
        return string.length();
    }
}
