/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/27 — generated by GEMINI.
 * Task: HE-027_flipCase
 */
public class HE027_flipCase {
    /**
     * For a given string, flip lowercase characters to uppercase and uppercase to lowercase.
     *     >>> flipCase("Hello")
     *     "hELLO"
     */
    public String flipCase(String string) {
        StringBuilder sb = new StringBuilder();
        for (char c : string.toCharArray()) {
            if (Character.isUpperCase(c)) sb.append(Character.toLowerCase(c));
            else if (Character.isLowerCase(c)) sb.append(Character.toUpperCase(c));
            else sb.append(c);
        }
        return sb.toString();
    }
}
