/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/24 — generated by GEMINI.
 * Task: HE-024_largestDivisor
 */
public class HE024_largestDivisor {
    /**
     * For a given number n, find the largest number that divides n evenly, smaller than n
     *     >>> largestDivisor(15)
     *     5
     */
    public int largestDivisor(int n) {
        for (int i = n - 1; i > 0; i--) {
            if (n % i == 0) return i;
        }
        return 1;
    }
}
