/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/31 — generated by GEMINI.
 * Task: HE-031_isPrime
 */
public class HE031_isPrime {
    /**
     * Return true if a given number is prime, and false otherwise.
     *     >>> isPrime(6)
     *     false
     *     >>> isPrime(101)
     *     true
     *     >>> isPrime(11)
     *     true
     *     >>> isPrime(13441)
     *     true
     *     >>> isPrime(61)
     *     true
     *     >>> isPrime(4)
     *     false
     *     >>> isPrime(1)
     *     false
     */
    public boolean isPrime(int n) {
        if (n < 2) return false;
        if (n == 2) return true;
        if (n % 2 == 0) return false;
        for (int i = 3; i * i <= n; i += 2) {
            if (n % i == 0) return false;
        }
        return true;
    }
}
