/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/35 — generated by GEMINI.
 * Task: HE-035_maxElement
 */
public class HE035_maxElement {
    /**
     * Return maximum element in the list.
     *     >>> maxElement(Arrays.asList(1, 2, 3))
     *     3
     *     >>> maxElement(Arrays.asList(5, 3, -5, 2, -3, 3, 9, 0, 123, 1, -10))
     *     123
     */
    public int maxElement(List<Integer> l) {
        return Collections.max(l);
    }
}
