/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/34 — generated by GEMINI.
 * Task: HE-034_unique
 */
public class HE034_unique {
    /**
     * Return sorted unique elements in a list
     *     >>> unique(Arrays.asList(5, 3, 5, 2, 3, 3, 9, 0, 123))
     *     [0, 2, 3, 5, 9, 123]
     */
    public List<Integer> unique(List<Integer> l) {
        return new ArrayList<>(new java.util.TreeSet<>(l));
    }
}
