/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;
import java.util.stream.Collectors;

/**
 * HumanEval Java/42 — generated by GEMINI.
 * Task: HE-042_incrList
 */
public class HE042_incrList {
    /**
     * Return list with elements incremented by 1.
     *     >>> incrList(Arrays.asList(1, 2, 3))
     *     [2, 3, 4]
     *     >>> incrList(Arrays.asList(5, 3, 5, 2, 3, 3, 9, 0, 123))
     *     [6, 4, 6, 3, 4, 4, 10, 1, 124]
     */
    public List<Integer> incrList(List<Integer> l) {
        return l.stream().map(x -> x + 1).collect(java.util.stream.Collectors.toList());
    }
}
