/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;
import java.util.stream.Collectors;

/**
 * HumanEval Java/42 — generated by GEMINI.
 * Task: HE-042_incrList
 */
public class HE042_incrList {
    /**
     * Return list with elements incremented by 1.
     *     >>> incrList(Arrays.asList(1, 2, 3))
     *     [2, 3, 4]
     *     >>> incrList(Arrays.asList(5, 3, 5, 2, 3, 3, 9, 0, 123))
     *     [6, 4, 6, 3, 4, 4, 10, 1, 124]
     */
    public List<Integer> incrList(List<Integer> l) {
        return l.stream().map(x -> x + 1).collect(java.util.stream.Collectors.toList());
    }
}
