/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/55 — generated by GEMINI.
 * Task: HE-055_fib
 */
public class HE055_fib {
    /**
     * Return n-th Fibonacci number.
     *     >>> fib(10)
     *     55
     *     >>> fib(1)
     *     1
     *     >>> fib(8)
     *     21
     */
    public int fib(int n) {
        if (n == 0) return 0;
        if (n == 1) return 1;
        return fib(n - 1) + fib(n - 2);
    }
}
