/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/83 — generated by GEMINI.
 * Task: HE-083_startsOneEnds
 */
public class HE083_startsOneEnds {
    /**
     * Given a positive integer n, return the count of the numbers of n-digit
     *     positive integers that start or end with 1.
     */
    public int startsOneEnds(int n) {
        if (n == 1) return 1;
        
        int result = 18;
        for (int i = 0; i < n - 2; i++) {
            result *= 10;
        }
        return result;
    }
}
