/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/83 — generated by GEMINI.
 * Task: HE-083_startsOneEnds
 */
public class HE083_startsOneEnds {
    /**
     * Given a positive integer n, return the count of the numbers of n-digit
     *     positive integers that start or end with 1.
     */
    public int startsOneEnds(int n) {
        if (n == 1) return 1;
        return (int) Math.pow(10, n - 1);
    }
}
