/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/109 — generated by GEMINI.
 * Task: HE-109_moveOneBall
 */
public class HE109_moveOneBall {
    /**
     * We have an array 'arr' of N integers arr[1], arr[2], ..., arr[N].The
     *     numbers in the array will be randomly ordered. Your task is to determine if
     *     it is possible to get an array sorted in non-decreasing order by performing
     *     the following operation on the given array:
     *         You are allowed to perform right shift operation any number of times.
     * 
     *     One right shift operation means shifting all elements of the array by one
     *     position in the right direction. The last element of the array will be moved to
     *     the starting position in the array i.e. 0th index.
     * 
     *     If it is possible to obtain the sorted array by performing the above operation
     *     then return true else return False.
     *     If the given array is empty then return true.
     * 
     *     Note: The given list is guaranteed to have unique elements.
     * 
     *     For Example:
     * 
     *     moveOneBall(Arrays.asList(3, 4, 5, 1, 2))==>true
     *     Explanation: By performin 2 right shift operations, non-decreasing order can
     *                  be achieved for the given array.
     *     moveOneBall(Arrays.asList(3, 5, 4, 1, 2))==>False
     *     Explanation:It is not possible to get non-decreasing order for the given
     *                 array by performing any number of right shift operations.
     */
    public boolean moveOneBall(List<Integer> arr) {
        if (arr.isEmpty()) return true;
        int minVal = Collections.min(arr);
        int idx = arr.indexOf(minVal);
        for (int i = 0; i < arr.size() - 1; i++) {
            int cur = arr.get((idx + i) % arr.size());
            int nxt = arr.get((idx + i + 1) % arr.size());
            if (cur > nxt) return false;
        }
        return true;
    }
}
