/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/126 — generated by GEMINI.
 * Task: HE-126_isSorted
 */
public class HE126_isSorted {
    /**
     * Given a list of numbers, return whether or not they are sorted
     *     in ascending order. If list has more than 1 duplicate of the same
     *     number, return false. Assume no negative numbers and only integers.
     * 
     *     Examples
     *     isSorted(Arrays.asList(5)) -> true
     *     isSorted(Arrays.asList(1, 2, 3, 4, 5)) -> true
     *     isSorted(Arrays.asList(1, 3, 2, 4, 5)) -> false
     *     isSorted(Arrays.asList(1, 2, 3, 4, 5, 6)) -> true
     *     isSorted(Arrays.asList(1, 2, 3, 4, 5, 6, 7)) -> true
     *     isSorted(Arrays.asList(1, 3, 2, 4, 5, 6, 7)) -> false
     *     isSorted(Arrays.asList(1, 2, 2, 3, 3, 4)) -> true
     *     isSorted(Arrays.asList(1, 2, 2, 2, 3, 4)) -> false
     */
    public boolean isSorted(List<Integer> lst) {
        for (int i = 0; i < lst.size() - 1; i++) {
            if (lst.get(i) > lst.get(i + 1)) return false;
        }
        Map<Integer, Integer> counts = new HashMap<>();
        for (int x : lst) counts.merge(x, 1, Integer::sum);
        for (int c : counts.values()) if (c > 2) return false;
        return true;
    }
}
