/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/132 — generated by GEMINI.
 * Task: HE-132_isNested
 */
public class HE132_isNested {
    /**
     * Create a function that takes a string as input which contains only square brackets.
     *     The function should return true if and only if there is a valid subsequence of brackets
     *     where at least one bracket in the subsequence is nested.
     * 
     *     isNested("[[]]") -> true
     *     isNested("[]]]]]]][[[[[]") -> false
     *     isNested("[][]") -> false
     *     isNested("[]") -> false
     *     isNested("[[][]]") -> true
     *     isNested("[[]][[") -> true
     */
    public boolean isNested(String string) {
        int depth = 0;
        for (char c : string.toCharArray()) {
            if (c == '[') {
                depth++;
            } else if (c == ']') {
                if (depth >= 2) return true;
                if (depth > 0) depth--;
            }
        }
        return false;
    }
}
