/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.gemini;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/139 — generated by GEMINI.
 * Task: HE-139_specialFactorial
 */
public class HE139_specialFactorial {
    /**
     * The Brazilian factorial is defined as:
     *     brazilian_factorial(n) = n! * (n-1)! * (n-2)! * ... * 1!
     *     where n > 0
     * 
     *     For example:
     *     >>> specialFactorial(4)
     *     288
     * 
     *     The function will receive an integer as input and should return the special
     *     factorial of this integer.
     */
    public long specialFactorial(int n) {
        long result = 1;
        long fact = 1;
        for (int i = 1; i <= n; i++) {
            fact *= i;
            result *= fact;
        }
        return result;
    }
}
