/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722,  150200018,        150210089
 */
package edu.itu.blg475e.phase2;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * BookScan — scans a multi-line text and reports how many times words of a
 * given length appear and on which lines they occur.
 *
 * <p>Generated by Gemini 2.5 Pro. Integrates three HumanEval-X methods:
 * <ul>
 *   <li>HE-018 {@link #howManyTimes(String, String)} — substring count</li>
 *   <li>HE-023 {@link #strlen(String)}               — string length</li>
 *   <li>HE-027 {@link #flipCase(String)}             — upper/lower flip</li>
 * </ul>
 *
 * <p><b>Known divergence:</b> {@link #howManyTimes(String, String)} returns
 * {@code string.length() + 1} for an empty {@code substring}, whereas the
 * canonical HumanEval expected value is {@code 0}. This is a Gemini-specific
 * generation artefact surfaced by integration test IT-HE018-EmptySubstring.
 */
public class BookScanGemini {

    // -----------------------------------------------------------------------
    // HE-023: Return length of given string
    // -----------------------------------------------------------------------

    /**
     * Return length of given string.
     *
     * @param string the input string
     * @return number of characters
     */
    public int strlen(String string) {
        return string.length();
    }

    // -----------------------------------------------------------------------
    // HE-018: Find how many times substring appears (overlapping)
    // -----------------------------------------------------------------------

    /**
     * Find how many times a given substring can be found in the original
     * string. Counts overlapping cases.
     *
     * <p><b>Note:</b> returns {@code string.length() + 1} for empty substring
     * (Gemini-specific divergence).
     *
     * @param string    text to search in
     * @param substring pattern to look for
     * @return number of occurrences
     */
    public int howManyTimes(String string, String substring) {
        if (substring.isEmpty()) return string.length() + 1;
        if (substring.length() > string.length()) return 0;

        int count = 0;
        for (int i = 0; i <= string.length() - substring.length(); i++) {
            if (string.substring(i, i + substring.length()).equals(substring)) {
                count++;
            }
        }
        return count;
    }

    // -----------------------------------------------------------------------
    // HE-027: Flip lowercase ↔ uppercase
    // -----------------------------------------------------------------------

    /**
     * For a given string, flip lowercase characters to uppercase and
     * uppercase to lowercase.
     *
     * @param string input string
     * @return case-flipped string
     */
    public String flipCase(String string) {
        StringBuilder sb = new StringBuilder();
        for (char c : string.toCharArray()) {
            if (Character.isUpperCase(c)) sb.append(Character.toLowerCase(c));
            else if (Character.isLowerCase(c)) sb.append(Character.toUpperCase(c));
            else sb.append(c);
        }
        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Core BookScan: count words of given length across the whole text
    // -----------------------------------------------------------------------

    /**
     * Counts how many words in {@code text} have exactly {@code targetLen}
     * characters. Uses {@link #strlen(String)} (HE-023) internally.
     *
     * @param text      multi-line input text
     * @param targetLen exact word length to match (≥ 1)
     * @return total count of matching words
     * @throws IllegalArgumentException if targetLen &lt; 1
     */
    public int countWordsOfLength(String text, int targetLen) {
        if (targetLen < 1) {
            throw new IllegalArgumentException(
                    "targetLen must be >= 1, got: " + targetLen);
        }
        int total = 0;
        for (String line : text.split("\n", -1)) {
            for (String word : tokenize(line)) {
                if (strlen(word) == targetLen) {   // HE-023
                    total++;
                }
            }
        }
        return total;
    }

    // -----------------------------------------------------------------------
    // Core BookScan: find line numbers containing words of given length
    // -----------------------------------------------------------------------

    /**
     * Returns the 1-based line numbers on which at least one word of length
     * {@code targetLen} appears. Uses {@link #strlen(String)} (HE-023),
     * {@link #flipCase(String)} (HE-027), and
     * {@link #howManyTimes(String, String)} (HE-018) internally.
     *
     * @param text      multi-line input text
     * @param targetLen exact word length to match (≥ 1)
     * @return sorted list of 1-based line indices; empty if none found
     * @throws IllegalArgumentException if targetLen &lt; 1
     */
    public List<Integer> linesContainingWordsOfLength(String text, int targetLen) {
        if (targetLen < 1) {
            throw new IllegalArgumentException(
                    "targetLen must be >= 1, got: " + targetLen);
        }
        List<Integer> result = new ArrayList<>();
        String[] lines = text.split("\n", -1);
        for (int i = 0; i < lines.length; i++) {
            boolean found = false;
            for (String word : tokenize(lines[i])) {
                if (strlen(word) == targetLen) {           // HE-023
                    found = true;
                    String flipped = flipCase(word);       // HE-027
                    howManyTimes(lines[i], flipped);       // HE-018
                }
            }
            if (found) {
                result.add(i + 1);
            }
        }
        return result;
    }

    // -----------------------------------------------------------------------
    // Core BookScan: full scan — map each word-length to its line numbers
    // -----------------------------------------------------------------------

    /**
     * Produces a complete scan of {@code text}. For every distinct word
     * length, the map value is the list of 1-based line numbers on which a
     * word of that length appears. Uses insertion-order LinkedHashMap.
     *
     * @param text multi-line input text
     * @return map from word-length to list of line numbers
     */
    public Map<Integer, List<Integer>> scanByWordLength(String text) {
        Map<Integer, List<Integer>> result = new LinkedHashMap<>();
        String[] lines = text.split("\n", -1);
        for (int i = 0; i < lines.length; i++) {
            int lineNumber = i + 1;
            for (String word : tokenize(lines[i])) {
                int len = strlen(word);   // HE-023
                result.computeIfAbsent(len, k -> new ArrayList<>()).add(lineNumber);
            }
        }
        return result;
    }

    // -----------------------------------------------------------------------
    // Helper
    // -----------------------------------------------------------------------

    /**
     * Splits a line on whitespace, strips leading/trailing punctuation, and
     * returns only non-empty lower-cased tokens.
     */
    private List<String> tokenize(String line) {
        List<String> tokens = new ArrayList<>();
        for (String raw : line.split("\\s+")) {
            String cleaned = raw.replaceAll("^[^a-zA-Z0-9]+|[^a-zA-Z0-9]+$", "")
                                .toLowerCase();
            if (!cleaned.isEmpty()) {
                tokens.add(cleaned);
            }
        }
        return tokens;
    }
}
