/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/7 — generated by CHATGPT.
 * Task: HE-007_filterBySubstring
 */
public class HE007_filterBySubstring {
    /**
     * Filter an input list of strings only for ones that contain given substring
     *     >>> filterBySubstring(List.of(), "a")
     *     []
     *     >>> filterBySubstring(Arrays.asList("abc", "bacd", "cde", "array"), "a")
     *     ["abc", "bacd", "array"]
     */
    public List<String> filterBySubstring(List<String> strings, String substring) {
        List<String> result = new ArrayList<>();
        for (String x : strings) {
            if (x.contains(substring)) {
                result.add(x);
            }
        }
        return result;
    }
}
