/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/3 — generated by CHATGPT.
 * Task: HE-003_belowZero
 */
public class HE003_belowZero {
    /**
     * You're given a list of deposit and withdrawal operations on a bank account that starts with
     *     zero balance. Your task is to detect if at any point the balance of account fallls below zero, and
     *     at that point function should return True. Otherwise it should return False.
     *     >>> belowZero(Arrays.asList(1, 2, 3))
     *     false
     *     >>> belowZero(Arrays.asList(1, 2, -4, 5))
     *     true
     */
    public boolean belowZero(List<Integer> operations) {
        int balance = 0;

        for (int op : operations) {
            balance += op;
            if (balance < 0) {
                return true;
            }
        }

        return false;
    }
}
