/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/15 — generated by CHATGPT.
 * Task: HE-015_stringSequence
 */
public class HE015_stringSequence {
    /**
     * Return a string containing space-delimited numbers starting from 0 upto n inclusive.
     *     >>> stringSequence(0)
     *     "0"
     *     >>> stringSequence(5)
     *     "0 1 2 3 4 5"
     */
    public String stringSequence(int n) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < n; i++) {
            sb.append(i);
            sb.append(" ");
        }
        sb.append(n);
        return sb.toString();
    }
}
