/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/14 — generated by CHATGPT.
 * Task: HE-014_allPrefixes
 */
public class HE014_allPrefixes {
    /**
     * Return list of all prefixes from shortest to longest of the input string
     *     >>> allPrefixes("abc")
     *     ["a", "ab", "abc"]
     */
    public List<String> allPrefixes(String string) {
        List<String> result = new ArrayList<>();

        for (int i = 1; i <= string.length(); i++) {
            result.add(string.substring(0, i));
        }
        return result;
    }
}
