/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/17 — generated by CHATGPT.
 * Task: HE-017_parseMusic
 */
public class HE017_parseMusic {
    /**
     * Input to this function is a string representing musical notes in a special ASCII format.
     *     Your task is to parse this string and return list of integers corresponding to how many beats does each
     *     not last.
     * 
     *     Here is a legend:
     *     "o" - whole note, lasts four beats
     *     "o|" - half note, lasts two beats
     *     ".|" - quater note, lasts one beat
     * 
     *     >>> parseMusic("o o| .| o| o| .| .| .| .| o o")
     *     [4, 2, 1, 2, 2, 1, 1, 1, 1, 4, 4]
     */
    public List<Integer> parseMusic(String string) {
        String[] notes = string.split(" ");
        List<Integer> result = new ArrayList<>();
        for (String s : notes) {
            switch (s) {
                case "o" -> result.add(4);
                case "o|" -> result.add(2);
                case ".|" -> result.add(1);
            }
        }
        return result;
    }
}
