/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/18 — generated by CHATGPT.
 * Task: HE-018_howManyTimes
 */
public class HE018_howManyTimes {
    /**
     * Find how many times a given substring can be found in the original string. Count overlaping cases.
     *     >>> howManyTimes("", "a")
     *     0
     *     >>> howManyTimes("aaa", "a")
     *     3
     *     >>> howManyTimes("aaaa", "aa")
     *     3
     */
    public int howManyTimes(String string, String substring) {
        int times = 0;

        for (int i = 0; i < string.length() - substring.length() + 1; i++) {
            if (string.substring(i, i + substring.length()).equals(substring)) {
                times += 1;
            }
        }

        return times;
    }
}
