/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/18 — generated by CHATGPT.
 * Task: HE-018_howManyTimes
 */
public class HE018_howManyTimes {
    /**
     * Find how many times a given substring can be found in the original string. Count overlaping cases.
     *     >>> howManyTimes("", "a")
     *     0
     *     >>> howManyTimes("aaa", "a")
     *     3
     *     >>> howManyTimes("aaaa", "aa")
     *     3
     */
    public int howManyTimes(String string, String substring) {
        int times = 0;

        for (int i = 0; i < string.length() - substring.length() + 1; i++) {
            if (string.substring(i, i + substring.length()).equals(substring)) {
                times += 1;
            }
        }

        return times;
    }
}
