/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/12 — generated by CHATGPT.
 * Task: HE-012_longest
 */
public class HE012_longest {
    /**
     * Out of list of strings, return the longest one. Return the first one in case of multiple
     *     strings of the same length. Return None in case the input list is empty.
     *     >>> longest(List.of())
     *     Optional.empty
     *     >>> longest(Arrays.asList("a", "b", "c"))
     *     Optional[a]
     *     >>> longest(Arrays.asList("a", "bb", "ccc"))
     *     Optional[ccc]
     */
    public Optional<String> longest(List<String> strings) {
        if (strings.isEmpty()) {
            return Optional.empty();
        }
        String longest = strings.get(0);
        for (String s : strings) {
            if (s.length() > longest.length()) {
                longest = s;
            }
        }
        return Optional.of(longest);
    }
}
