/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/23 — generated by CHATGPT.
 * Task: HE-023_strlen
 */
public class HE023_strlen {
    /**
     * Return length of given string
     *     >>> strlen("")
     *     0
     *     >>> strlen("abc")
     *     3
     */
    public int strlen(String string) {
        return string.length();
    }
}
