/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/24 — generated by CHATGPT.
 * Task: HE-024_largestDivisor
 */
public class HE024_largestDivisor {
    /**
     * For a given number n, find the largest number that divides n evenly, smaller than n
     *     >>> largestDivisor(15)
     *     5
     */
    public int largestDivisor(int n) {
        for (int i = n - 1; i > 0; i--) {
            if (n % i == 0) {
                return i;
            }
        }
        return 1;
    }
}
