/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/28 — generated by CHATGPT.
 * Task: HE-028_concatenate
 */
public class HE028_concatenate {
    /**
     * Concatenate list of strings into a single string
     *     >>> concatenate(List.of())
     *     ""
     *     >>> concatenate(Arrays.asList("a", "b", "c"))
     *     "abc"
     */
    public String concatenate(List<String> strings) {
        return String.join("", strings);
    }
}
