/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/25 — generated by CHATGPT.
 * Task: HE-025_factorize
 */
public class HE025_factorize {
    /**
     * Return list of prime factors of given integer in the order from smallest to largest.
     *     Each of the factors should be listed number of times corresponding to how many times it appeares in factorization.
     *     Input number should be equal to the product of all factors
     *     >>> factorize(8)
     *     [2, 2, 2]
     *     >>> factorize(25)
     *     [5, 5]
     *     >>> factorize(70)
     *     [2, 5, 7]
     */
    public List<Integer> factorize(int n) {
        List<Integer> fact = new ArrayList<>();
        int i = 2;
        while (n > 1) {
            if (n % i == 0) {
                fact.add(i);
                n /= i;
            } else {
                i++;
            }
        }
        return fact;
    }
}
