/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/27 — generated by CHATGPT.
 * Task: HE-027_flipCase
 */
public class HE027_flipCase {
    /**
     * For a given string, flip lowercase characters to uppercase and uppercase to lowercase.
     *     >>> flipCase("Hello")
     *     "hELLO"
     */
    public String flipCase(String string) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < string.length(); i++) {
            if (Character.isLowerCase(string.charAt(i))) {
                sb.append(Character.toUpperCase(string.charAt(i)));
            } else {
                sb.append(Character.toLowerCase(string.charAt(i)));
            }
        }
        return sb.toString();
    }
}
