/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/31 — generated by CHATGPT.
 * Task: HE-031_isPrime
 */
public class HE031_isPrime {
    /**
     * Return true if a given number is prime, and false otherwise.
     *     >>> isPrime(6)
     *     false
     *     >>> isPrime(101)
     *     true
     *     >>> isPrime(11)
     *     true
     *     >>> isPrime(13441)
     *     true
     *     >>> isPrime(61)
     *     true
     *     >>> isPrime(4)
     *     false
     *     >>> isPrime(1)
     *     false
     */
    public boolean isPrime(int n) {
        if (n < 2) {
            return false;
        }
        for (int k = 2; k < n; k++) {
            if (n % k == 0) {
                return false;
            }
        }
         return true;
    }
}
