/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/34 — generated by CHATGPT.
 * Task: HE-034_unique
 */
public class HE034_unique {
    /**
     * Return sorted unique elements in a list
     *     >>> unique(Arrays.asList(5, 3, 5, 2, 3, 3, 9, 0, 123))
     *     [0, 2, 3, 5, 9, 123]
     */
    public List<Integer> unique(List<Integer> l) {
        List<Integer> result = new ArrayList<>(new HashSet<>(l));
        Collections.sort(result);
        return result;
    }
}
