/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/31 — generated by CHATGPT.
 * Task: HE-031_isPrime
 */
public class HE031_isPrime {
    /**
     * Return true if a given number is prime, and false otherwise.
     *     >>> isPrime(6)
     *     false
     *     >>> isPrime(101)
     *     true
     *     >>> isPrime(11)
     *     true
     *     >>> isPrime(13441)
     *     true
     *     >>> isPrime(61)
     *     true
     *     >>> isPrime(4)
     *     false
     *     >>> isPrime(1)
     *     false
     */
    public boolean isPrime(int n) {
        if (n < 2) {
            return false;
        }
        for (int k = 2; k < n; k++) {
            if (n % k == 0) {
                return false;
            }
        }
         return true;
    }
}
