/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/35 — generated by CHATGPT.
 * Task: HE-035_maxElement
 */
public class HE035_maxElement {
    /**
     * Return maximum element in the list.
     *     >>> maxElement(Arrays.asList(1, 2, 3))
     *     3
     *     >>> maxElement(Arrays.asList(5, 3, -5, 2, -3, 3, 9, 0, 123, 1, -10))
     *     123
     */
    public int maxElement(List<Integer> l) {
        return Collections.max(l);
    }
}
