/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/47 — generated by CHATGPT.
 * Task: HE-047_median
 */
public class HE047_median {
    /**
     * Return median of elements in the list l.
     *     >>> median(Arrays.asList(3, 1, 2, 4, 5))
     *     3
     *     >>> median(Arrays.asList(-10, 4, 6, 1000, 10, 20))
     *     15.0
     */
    public double median(List<Integer> l) {
        List<Integer> list = l;
        Collections.sort(list);
        if (l.size() % 2 == 1) {
            return l.get(l.size() / 2);
        } else {
            return (l.get(l.size() / 2 - 1) + l.get(l.size() / 2)) / 2.0;
        }
    }
}
