/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/47 — generated by CHATGPT.
 * Task: HE-047_median
 */
public class HE047_median {
    /**
     * Return median of elements in the list l.
     *     >>> median(Arrays.asList(3, 1, 2, 4, 5))
     *     3
     *     >>> median(Arrays.asList(-10, 4, 6, 1000, 10, 20))
     *     15.0
     */
    public double median(List<Integer> l) {
        List<Integer> list = l;
        Collections.sort(list);
        if (l.size() % 2 == 1) {
            return l.get(l.size() / 2);
        } else {
            return (l.get(l.size() / 2 - 1) + l.get(l.size() / 2)) / 2.0;
        }
    }
}
