/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;
import java.util.stream.Collectors;

/**
 * HumanEval Java/42 — generated by CHATGPT.
 * Task: HE-042_incrList
 */
public class HE042_incrList {
    /**
     * Return list with elements incremented by 1.
     *     >>> incrList(Arrays.asList(1, 2, 3))
     *     [2, 3, 4]
     *     >>> incrList(Arrays.asList(5, 3, 5, 2, 3, 3, 9, 0, 123))
     *     [6, 4, 6, 3, 4, 4, 10, 1, 124]
     */
    public List<Integer> incrList(List<Integer> l) {
        return l.stream().map(p -> p + 1).collect(Collectors.toList());
    }
}
