/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/72 — generated by CHATGPT.
 * Task: HE-072_willItFly
 */
public class HE072_willItFly {
    /**
     * Write a function that returns True if the object q will fly, and False otherwise.
     *     The object q will fly if it's balanced (it is a palindromic list) and the sum of its elements is less than or equal the maximum possible weight w.
     * 
     *     Example:
     *     willItFly(Arrays.asList(1, 2), 5) -> false
     *     # 1+2 is less than the maximum possible weight, but it's unbalanced.
     * 
     *     willItFly(Arrays.asList(3, 2, 3), 1) -> false
     *     # it's balanced, but 3+2+3 is more than the maximum possible weight.
     * 
     *     willItFly(Arrays.asList(3, 2, 3), 9) -> true
     *     # 3+2+3 is less than the maximum possible weight, and it's balanced.
     * 
     *     willItFly(Arrays.asList(3), 5) -> true
     *     # 3 is less than the maximum possible weight, and it's balanced.
     */
    public boolean willItFly(List<Integer> q, int w) {
        if (q.stream().reduce(0, Integer::sum) > w) {
            return false;
        }
        int i = 0, j = q.size() - 1;
        while (i < j) {
            if (!Objects.equals(q.get(i), q.get(j))) {
                return false;
            }
            i += 1;
            j -= 1;
        }
        return true;
    }
}
