/* @Authors
 * Mert Aydın - 150220722
 * Oğuz Eren Kacar - 150200018
 * Mehmet Enes Tekgöz - 150210089
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/83 — generated by CHATGPT.
 * Task: HE-083_startsOneEnds
 */
public class HE083_startsOneEnds {
    /**
     * Given a positive integer n, return the count of the numbers of n-digit
     *     positive integers that start or end with 1.
     */
    public int startsOneEnds(int n) {
        if (n == 1) {
            return 1;
        }
        return 18 * (int) Math.pow(10, n - 2);
    }
}
