/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/126 — generated by CHATGPT.
 * Task: HE-126_isSorted
 */
public class HE126_isSorted {
    /**
     * Given a list of numbers, return whether or not they are sorted
     *     in ascending order. If list has more than 1 duplicate of the same
     *     number, return false. Assume no negative numbers and only integers.
     * 
     *     Examples
     *     isSorted(Arrays.asList(5)) -> true
     *     isSorted(Arrays.asList(1, 2, 3, 4, 5)) -> true
     *     isSorted(Arrays.asList(1, 3, 2, 4, 5)) -> false
     *     isSorted(Arrays.asList(1, 2, 3, 4, 5, 6)) -> true
     *     isSorted(Arrays.asList(1, 2, 3, 4, 5, 6, 7)) -> true
     *     isSorted(Arrays.asList(1, 3, 2, 4, 5, 6, 7)) -> false
     *     isSorted(Arrays.asList(1, 2, 2, 3, 3, 4)) -> true
     *     isSorted(Arrays.asList(1, 2, 2, 2, 3, 4)) -> false
     */
    public boolean isSorted(List<Integer> lst) {
        List<Integer> sorted_lst = new ArrayList<>(lst);
        Collections.sort(sorted_lst);
        if (!lst.equals(sorted_lst)) {
            return false;
        }
        for (int i = 0; i < lst.size() - 2; i++) {
            if (lst.get(i) == lst.get(i + 1) && lst.get(i) == lst.get(i + 2)) {
                return false;
            }
        }
        return true;
    }
}
