/* @Authors
 * Student Names: <Student 1>, <Student 2>, <Student 3>
 * Student IDs:   <ID 1>, <ID 2>, <ID 3>
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
package edu.itu.blg475e.chatgpt;

import java.util.*;
import java.lang.*;

/**
 * HumanEval Java/139 — generated by CHATGPT.
 * Task: HE-139_specialFactorial
 */
public class HE139_specialFactorial {
    /**
     * The Brazilian factorial is defined as:
     *     brazilian_factorial(n) = n! * (n-1)! * (n-2)! * ... * 1!
     *     where n > 0
     * 
     *     For example:
     *     >>> specialFactorial(4)
     *     288
     * 
     *     The function will receive an integer as input and should return the special
     *     factorial of this integer.
     */
    public long specialFactorial(int n) {
        long fact_i = 1, special_fact = 1;
        for (int i = 1; i <= n; i++) {
            fact_i *= i;
            special_fact *= fact_i;
        }
        return special_fact;
    }
}
