#!/usr/bin/env python3
"""Aggregate JaCoCo CSV into a per-problem markdown table for the report."""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT / "report" / "coverage" / "jacocoTestReport.csv"
OUT = ROOT / "report" / "coverage" / "coverage_summary.md"


def main():
    rows = list(csv.DictReader(CSV.open()))
    # Separate by package (chatgpt vs gemini)
    by_pkg = {"chatgpt": [], "gemini": []}
    for r in rows:
        pkg = r["PACKAGE"].rsplit(".", 1)[-1]
        if pkg in by_pkg:
            by_pkg[pkg].append(r)

    lines = ["# JaCoCo Coverage Summary — Phase 1\n"]
    lines.append("_Generated by `scripts/build_coverage_summary.py` after `./gradlew test jacocoTestReport`._\n")
    for llm in ("chatgpt", "gemini"):
        lines.append(f"\n## {llm.upper()}\n")
        lines.append("| Class | Lines (covered/total) | Branch (covered/total) | Branch % |")
        lines.append("|---|---|---|---|")
        total_bc = total_bt = total_lc = total_lt = 0
        for r in sorted(by_pkg[llm], key=lambda x: x["CLASS"]):
            lm, lc = int(r["LINE_MISSED"]), int(r["LINE_COVERED"])
            bm, bc = int(r["BRANCH_MISSED"]), int(r["BRANCH_COVERED"])
            lt = lm + lc
            bt = bm + bc
            pct = f"{100.0*bc/bt:.1f}%" if bt else "N/A"
            total_lc += lc; total_lt += lt; total_bc += bc; total_bt += bt
            lines.append(f"| {r['CLASS']} | {lc}/{lt} | {bc}/{bt} | {pct} |")
        pct_l = f"{100.0*total_lc/total_lt:.1f}%" if total_lt else "N/A"
        pct_b = f"{100.0*total_bc/total_bt:.1f}%" if total_bt else "N/A"
        lines.append(f"| **TOTAL** | **{total_lc}/{total_lt} ({pct_l})** | **{total_bc}/{total_bt}** | **{pct_b}** |")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
