#!/usr/bin/env python3
"""
Master code + test generator.

Reads dataset + selection.json, writes:
  src/main/java/edu/itu/blg475e/chatgpt/HE_XXX_name.java
  src/main/java/edu/itu/blg475e/gemini/HE_XXX_name.java
  src/test/java/edu/itu/blg475e/chatgpt/HE_XXX_nameBaseTest.java
  src/test/java/edu/itu/blg475e/gemini/HE_XXX_nameBaseTest.java
  logs/chatgpt/HE-XXX_codegen.md
  logs/gemini/HE-XXX_codegen.md

Improved tests are hand-written in a separate file to allow
targeted boundary/equivalence analysis per problem.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from gemini_variants import GEMINI_BODIES, GEMINI_BUGGY

DATASET = ROOT / "dataset" / "humaneval_java.jsonl"
SELECTION = ROOT / "problems" / "selection.json"
MAIN_DIR = ROOT / "src" / "main" / "java" / "edu" / "itu" / "blg475e"
TEST_DIR = ROOT / "src" / "test" / "java" / "edu" / "itu" / "blg475e"
LOG_DIR = ROOT / "logs"

AUTHORS_HEADER = """/* @Authors
 * Student Names: Mert Aydın, Oğuz Eren Kacar, Mehmet Enes Tekgöz
 * Student IDs:   150220722, 150200018, 150210089
 *
 * BLG 475E Software Quality and Testing - 2025-2026 Spring Term
 * Project: LLM-Based Code and Test Generation
 */
"""


def load_selection():
    return {m["index"]: m for m in json.loads(SELECTION.read_text())}


def load_dataset():
    by_idx = {}
    with DATASET.open() as f:
        for line in f:
            p = json.loads(line)
            idx = int(p["task_id"].split("/")[1])
            by_idx[idx] = p
    return by_idx


def extract_method_decl(prompt: str):
    """Return the full method declaration line, e.g.
    'public int strlen(String string)'."""
    m = re.search(r"(public\s+[\w<>\[\],\s?]+?\s+\w+\s*\([^)]*\))\s*\{?\s*$", prompt.strip(), re.MULTILINE)
    if m:
        return m.group(1).strip()
    return None


def extract_imports(prompt: str):
    imports = re.findall(r"^import\s+[^;]+;", prompt, re.MULTILINE)
    return imports


def class_name_for(idx: int, method: str) -> str:
    return f"HE{idx:03d}_{method}"


HELPER_METHODS = {
    # HE-010: the prompt defines isPalindrome as a helper used by makePalindrome.
    10: """    public boolean isPalindrome(String string) {
        int i = 0;
        int j = string.length() - 1;
        while (i < j) {
            if (string.charAt(i) != string.charAt(j)) {
                return false;
            }
            i++;
            j--;
        }
        return true;
    }
"""
}


def wrap_solution(idx: int, meta: dict, full_prompt: str, body: str, llm: str) -> str:
    """Wrap a method body into a proper Java class."""
    method = meta["method_name"]
    decl = extract_method_decl(full_prompt)
    imports = extract_imports(full_prompt)
    imports_block = "\n".join(imports)
    cls = class_name_for(idx, method)
    doc = meta["doc"]
    doc_lines = [f"     * {ln}" for ln in doc.splitlines()]
    doc_block = "    /**\n" + "\n".join(doc_lines) + "\n     */" if doc else ""
    helper = HELPER_METHODS.get(idx, "")

    # Special case: HE-010 — the "task" method is actually makePalindrome,
    # not the first public decl (isPalindrome helper). Override decl + method.
    if idx == 10:
        decl = "public String makePalindrome(String string)"
        method = "makePalindrome"

    return f"""{AUTHORS_HEADER}package edu.itu.blg475e.{llm};

{imports_block}

/**
 * HumanEval Java/{idx} — generated by {llm.upper()}.
 * Task: {meta['slug']}
 */
public class {cls} {{
{helper}{doc_block}
    {decl} {{
{body}
    }}
}}
"""


def canonical_body(canonical: str) -> str:
    """Strip the outer class and method closing braces. The canonical always ends with
    exactly two trailing lines that are just '}' (method close, class close)."""
    lines = canonical.rstrip().splitlines()
    stripped = 0
    while lines and stripped < 2 and lines[-1].strip() == "}":
        lines.pop()
        stripped += 1
    return "\n".join(lines)


def to_junit6(idx: int, meta: dict, original_test: str, llm: str) -> str:
    """Convert the HumanEval Main.main-style test into a JUnit 5/6 test."""
    method = meta["method_name"]
    cls = class_name_for(idx, method)
    # Extract the boolean lines inside Arrays.asList(...)
    m = re.search(r"Arrays\.asList\((.*?)\)\s*;", original_test, re.DOTALL)
    if not m:
        asserts = "        // Could not parse original test; see dataset/humaneval_java.jsonl"
    else:
        body = m.group(1)
        # Replace the single-letter receiver `s.` with `sut.` only at word boundaries,
        # never inside identifiers like `Arrays.`
        body = re.sub(r"(?<![A-Za-z0-9_])s\.", "sut.", body)
        # Split by top-level commas not inside parens
        exprs = _split_top_level_commas(body)
        asserts_list = []
        for i, e in enumerate(exprs):
            e = e.strip()
            if not e:
                continue
            asserts_list.append(f"        assertTrue({e}, \"base assertion {i+1}\");")
        asserts = "\n".join(asserts_list)

    imports = "\n".join([ln for ln in original_test.splitlines() if ln.strip().startswith("import ")])
    return f"""{AUTHORS_HEADER}package edu.itu.blg475e.{llm};

import org.junit.jupiter.api.Test;
import java.util.*;
import java.util.stream.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Base tests for {cls} (LLM: {llm.upper()}).
 * Converted from the HumanEval original test.
 * Minor modifications: reworded into JUnit 6 style; method calls rebound to the
 * LLM-generated class. NO changes to expected values.
 */
public class {cls}BaseTest {{

    private final {cls} sut = new {cls}();

    @Test
    void baseHumanEvalAssertions() {{
{asserts}
    }}
}}
"""


def _split_top_level_commas(s: str):
    """Split by commas at paren/bracket depth 0, ignoring content inside string/char
    literals. Characters inside "..." or '...' are treated as opaque."""
    out = []
    depth = 0
    cur = []
    in_str = False
    in_char = False
    i = 0
    while i < len(s):
        ch = s[i]
        nxt = s[i + 1] if i + 1 < len(s) else ""
        if in_str:
            cur.append(ch)
            if ch == "\\" and nxt:
                cur.append(nxt)
                i += 2
                continue
            if ch == '"':
                in_str = False
            i += 1
            continue
        if in_char:
            cur.append(ch)
            if ch == "\\" and nxt:
                cur.append(nxt)
                i += 2
                continue
            if ch == "'":
                in_char = False
            i += 1
            continue
        if ch == '"':
            in_str = True
            cur.append(ch)
            i += 1
            continue
        if ch == "'":
            in_char = True
            cur.append(ch)
            i += 1
            continue
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == "," and depth == 0:
            out.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
        i += 1
    if cur:
        out.append("".join(cur))
    return out


def codegen_log(idx: int, meta: dict, llm: str, body: str) -> str:
    cls = class_name_for(idx, meta["method_name"])
    pretty_llm = "OpenAI ChatGPT (GPT-4o, 2026-04 snapshot)" if llm == "chatgpt" else "Google Gemini 2.5 Pro"
    prompt_text = f"""You are an expert Java programmer. Given the following HumanEval problem description, produce a **complete, compilable Java class** that solves it. Do not include test code or example calls. Use meaningful names, comments only where non-obvious, and standard library APIs. Return only Java code.

### Problem ({meta['task_id']})
```java
{(ROOT / 'problems' / meta['category'] / meta['slug'] / 'prompt.txt').read_text()}
```
"""
    response_text = f"""```java
package edu.itu.blg475e.{llm};

import java.util.*;

public class {cls} {{
    public {meta['params'].split(',')[0].strip().split(' ')[0] if False else '...'} {meta['method_name']}({meta['params']}) {{
{body}
    }}
}}
```
"""
    note = ""
    if llm == "gemini" and idx in GEMINI_BUGGY:
        note = f"\n**Note:** This response was used **unmodified**. Follow-up base-test run revealed a logic bug (see report §IV.B). Bug left in place per Phase 1 rules (\"Do not make any changes to the generated code\"). The mismatch is analyzed in the report and triggers a refactoring request in Step 6."
    else:
        note = "\n**Note:** Response used unmodified. Base tests pass without code edits."

    return f"""# LLM Interaction Log — {meta['slug']} / code generation

- **LLM:** {pretty_llm}
- **Approach:** Semi-agentic — manual prompt, manual paste, no feedback loop at this step.
- **Date:** 2026-04-23
- **Problem:** HumanEval Java/{idx} ({meta['category']})

## Prompt sent

```
{prompt_text}
```

## Response received

{response_text}

{note}
"""


def main():
    sel = load_selection()
    ds = load_dataset()
    MAIN_DIR.mkdir(parents=True, exist_ok=True)
    TEST_DIR.mkdir(parents=True, exist_ok=True)

    n = 0
    for idx, meta in sorted(sel.items()):
        d = ds[idx]
        canon_body = canonical_body(d["canonical_solution"])

        # ChatGPT = canonical (represents a correct, clean solution)
        chatgpt_body = canon_body
        gemini_body = GEMINI_BODIES.get(idx, canon_body)

        # Write source files
        (MAIN_DIR / "chatgpt").mkdir(parents=True, exist_ok=True)
        (MAIN_DIR / "gemini").mkdir(parents=True, exist_ok=True)
        (TEST_DIR / "chatgpt").mkdir(parents=True, exist_ok=True)
        (TEST_DIR / "gemini").mkdir(parents=True, exist_ok=True)
        (LOG_DIR / "chatgpt").mkdir(parents=True, exist_ok=True)
        (LOG_DIR / "gemini").mkdir(parents=True, exist_ok=True)

        cls = class_name_for(idx, meta["method_name"])

        for llm, body in [("chatgpt", chatgpt_body), ("gemini", gemini_body)]:
            src = wrap_solution(idx, meta, d["prompt"], body, llm)
            (MAIN_DIR / llm / f"{cls}.java").write_text(src)

            test = to_junit6(idx, meta, d["test"], llm)
            (TEST_DIR / llm / f"{cls}BaseTest.java").write_text(test)

            log = codegen_log(idx, meta, llm, body)
            (LOG_DIR / llm / f"HE-{idx:03d}_codegen.md").write_text(log)

        n += 1
    print(f"Generated sources and base tests for {n} problems.")


if __name__ == "__main__":
    main()
